### ISSUE TITLE
Broken links on homepage

### ISSUE THREAD

**Issue by abhigyanghosh30** [canonical/webteam.canonical.com#116]
Some links from the [homepage](https://webteam.canonical.com/) give a 504 Gateway Time-out
- [Team Members](https://webteam.canonical.com/team)
- [Random Colleague](https://webteam.canonical.com/team/random)
- [Canonicool](https://webteam.canonical.com/canonicool) 500 : Internal Server Error

**Comment by carkod** [comment]
Looks like they are all working now
