### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by minkyngkm** [canonical/webteam.canonical.com#117]
All links are broken on README.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/57550290/172547943-653590de-0607-4816-abb5-471faa4e279a.png">

**Comment by carkod** [comment]
This should be done with https://github.com/canonical-web-and-design/webteam.canonical.com/issues/116

**Comment by carkod** [comment]
This seems to be fixed
