### ISSUE TITLE
Add "Training" page

### ISSUE THREAD

**Issue by nottrobin** [canonical/webteam.canonical.com#136]
Make a top-level "training" section which will include suggestions for training courses that people could do. This content should be pulled from ... Discourse? And be editable by all.

**Comment by sowasred2012** [comment]
@nottrobin triage this plssss

**Comment by sowasred2012** [comment]
Closing - this exists in JIRA now

**Comment by nottrobin** [comment]
@sowasred2012 is that how we're treating GitHub issues? Is that only because this is a feature request rather than a bug?

I would have thought it would be much better to have these somehow linked between Jira and GitHub, so this doesn't get closed until it's actually complete.

**Comment by sowasred2012** [comment]
@nottrobin I guess I don't see why we need an issue in GitHub and an issue in JIRA that just links to the GitHub issue. If we're trying to transition to JIRA, it seems like the best thing is to reduce noise/duplication and have JIRA be the place to track new features/pages/updates that we're proposing as a team.

**Comment by nottrobin** [comment]
@sowasred2012 the arguments for the duplication are:

- This is the list of issues about the project itself
- This is public

I agree that there's little point tracking private project management style tasks on both GitHub and Jira. I assume the squad repos will no longer exists anyway. There's certainly an argument to be had about whether private projects should still have issues lists or not - is it useful to have an issues list attached to the GitHub project or do we think that can be effectively replaced by Jira? We can continue that discussion.

But certainly some issues on public projects should remain, and as long as they remain, they should be accurately represented. As in, "closed" = completed. Otherwise they shouldn't exist. It would be nice if there was a way to link a Jira task with a GitHub issue such that when one was completed the other closed automatically.

I guess there's another argument as to whether there's any use in *this* issue being on GitHub. Maybe not. Maybe aspirational future tasks like this should only be tracked in a project management sense.

I'll leave this closed for now, but I do think we need to discuss and come to an understanding about all of these things.
