### ISSUE TITLE
Show information about deployments in progress

### ISSUE THREAD

**Issue by bartaz** [canonical/webteam.canonical.com#7]
It would be really useful to see if any staging (or ideally also production) deployment is in progress.

A helpful addition would be at least a link to jenkins (staging and production) to see current build or history of builds.

**Comment by nottrobin** [comment]
Here's what we can do easily:

- Add a link to the list of current builds for both staging and production
- Query the GitHub API to check the latest commit on `master` - then highlight somehow if the latest commit is not yet on staging, and encourage the reader to go and check if a build is in progress
- Also show which commit is on production, and therefore whether production is currently behind staging

However, it is certainly not trivial, and may not be possible, to actually detect whether a staging or production build is in progress.

**Comment by bartaz** [comment]
@nottrobin Having git commit id for GitHub, staging, production for comparison would be quite helpful already!

**Comment by carkod** [comment]
@nottrobin @bartaz guys I am thinking if this can be achieved with #17? The issue of having so many commit id is that we don't have enough space in the table

**Comment by bartaz** [comment]
TBH, it was such a long time ago that I don't really remember the context.

The original issue seems to be about showing if deployment is in progress, which doesn't seem to be addressed.
But I understand if there are technical limitations that make it hard to implement (getting current state of running jenkins job).
So I'm fine with closing this one if that's the case.
